<?php

/**
 * @file
 * Contains mt_react_demo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mt_react_demo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mt_react_demo module.
    case 'help.page.mt_react_demo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrates and injects a React app within the pages of Drupal.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_page().
 */
function mt_react_demo_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'mt_react_demo/mt_react_demo';
}

/**
 * Implements hook_page_bottom().
 */
function mt_react_demo_page_bottom(array &$page_bottom) {
  // Limit it for certain paths.
  // $search = 'manage/group/permissions';
  // $current_path = \Drupal::service('path.current')->getPath();
  // if (!str_contains($current_path, $search)) {
  //   return;
  // }
  $page_bottom['fut_group_permission_suggest']['button'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#attributes' => [
      'id' => 'root',
      'class' => 'root',
    ],
  ];
}
